---
- name: install essential packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - software-properties-common
    - build-essential
    - libssl-dev
    - libffi-dev
    - python
    - python-dev
    - python-pip

- name: upgrade pip
  pip:
    name: pip
    extra_args: --upgrade